### PR TITLE
Add person to entities

### PR DESCRIPTION
**Pull request by dafuga**
This PR finishes off the work that Josh started with his own PR.

Basically modified the person class as well as the persistence module to allow a friendlier interface on the apps side.

PS. I did a PR under /sheldond, but please let me know if I should just do PRs here from now on.

And just added is_slm_secure to ministries as well.

### CODE REVIEW

**Comment by sheldond** [comment]
Thanks! Regarding the nested authentication entity, this seems to work but it would be great if we could have a more generic solution for nested entities, so that we could easily support any nested entity attribute. Do you think it's worth looking into now, or should we leave that for another time?

**Comment by sheldond** [comment]
Oh and to answer your question: please submit PRs in this CruGlobal repo, we will retire the sheldond repo in favour of this one. Thanks :smile:

**Comment by dafuga** [comment]
Actually, I might be wrong but I think that the way things are set up we can give the create function both nested and not nested parameters. So I think that things are better this way.

**Comment by sheldond** [comment]
As an example, if we wanted to update a different attribute on authentication (e.g. relay_guid attribute), would we have to explicitly add that into persistence.rb and also to person.rb?

I suppose this might be premature optimization at this point, but something to think about if we need to handle more nested entities in the future.

**Comment by dafuga** [comment]
Well if you wanted to update a different attribute, you wouldn't have to touch the persistence module at all . You would simply add a way to store the nested attribute in the object class. I only made the change to the persistence module because I wanted the gem to handle both nested and non-nested forms of params for the case of authentication (To keep things simpler on the Ararat project). However, I do understand your point, if in the future we have more than one nested attributes that we wish to unnest (not sure I can say that :) ), it would be a good idea to move some of that logic into the object classes as opposed to having a bunch of if statements in the persistence module.

**Comment by sheldond** [comment]
Okay gotcha! Thanks for explaining! I think we can merge it now then.

**Comment by dafuga** [comment]
Thanks Sheldon :)

**Pull request merged**
